import Head from 'next/head';
import {useState} from 'react';
import Navbar from '../components/Navbar';
import About from '../components/About';
import Skills from '../components/Skills';
import Projects from '../components/Projects';

// To run: npm run dev
export default function Home() {
  const[darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Sai Sreshtaa's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Navbar /> */}
        <About />
        <Skills />      
        <Projects />                     
      </main>
    </div>
  )
}
